[package]
name = "wc"
version = "0.1.0"
authors = ["steve"]

[profile.release]
#lto=true
opt-level = 3
panic = 'abort'
debug-assertions = false
target-cpus='native'

[dependencies]
bytecount = "0.2.0"
clap = "2.29.0"
rand="0.3"
heapsize = "0.4.1"
libc = "0.2.34"
fnv = "1.0.3"


